cyto_file:
  "/mnt/data/ukbb_WGS/autosomal_files.txt"
plink_path:
  "/mnt/data/plink2"
keep_file:
  "/mnt/data/keep.txt"
MAC:
  '5'
HWE:
  "5e-8"
MAX_alleles:
  "3"
MISSING_per_person:
  "0.1"
MISSING_per_SNP:
  "0.1"